/**
 * Stage 5: `component-coverage.md`, written on every emit.
 *
 * The plan called this "a coverage report, not a silent pass". The pass is already enforced in code
 * — `ComponentMapper.blocks` throws on a component type that is in none of its tables, so an
 * unhandled construct cannot quietly vanish from 727 screens — and this is the other half: the list
 * of what the port does with each of the 51 types Direct File's flow actually declares, in a file a
 * reviewer can read without running anything.
 *
 * Generated rather than hand-kept, for the reason every generated file here is: a table of 51 rows
 * maintained by hand is a table that is wrong by the third upstream change, and being wrong about
 * what was dropped is exactly the failure this file exists to prevent.
 */
import type { ComponentCategory, ContentReport } from './content.ts';

type Components = ContentReport['components'];

interface Group {
  category: ComponentCategory;
  heading: string;
  blurb: string;
}

const GROUPS: Group[] = [
  {
    category: `expressed`,
    heading: `Expressed in the flow`,
    blurb:
      `Each becomes flow markup. Where a type has more than one row, its props decide: content ` +
      `marked \`displayOnlyOn: 'data-view'\` never appears on an editing screen, and a topic page ` +
      `is an editing screen.`,
  },
  {
    category: `rendered-elsewhere`,
    heading: `Drawn by something else`,
    blurb: `Present upstream as a component, present here as part of the page or the collection it sits in.`,
  },
  {
    category: `out-of-scope`,
    heading: `Out of scope`,
    blurb:
      `The port is questionnaire-only: no authentication, no MeF submission, no PDF, no data ` +
      `import, no state-tax handoff, no e-signature. These are the components that belong to those, ` +
      `listed so their absence is a decision on the record rather than a gap nobody noticed.`,
  },
  {
    category: `not-expressible`,
    heading: `Real gaps`,
    blurb: `Expressible in Direct File and not in this flow. Each is a thing to fix, not a thing to explain.`,
  },
];

/**
 * A disposition as a table cell.
 *
 * The dispositions name markup — `<fg-set> with <input type="address">` — and a bare `<input>` in a
 * Markdown table is an HTML tag, not text. Each angle-bracketed run becomes a code span, and a pipe
 * is escaped so it does not end the cell.
 */
function escapeCell(value: string): string {
  return value.replace(/<[^>]*>/g, (tag) => `\`${tag}\``).replace(/\|/g, `\\|`);
}

function table(components: Components, category: ComponentCategory): string {
  const rows = Object.entries(components)
    .filter(([, c]) => c.category === category)
    .sort(([a], [b]) => a.localeCompare(b));
  if (rows.length === 0) return `_None._\n`;

  const lines = [`| Component | Declarations | Becomes |`, `|---|---:|---|`];
  for (const [name, component] of rows) {
    for (const [index, { disposition, count }] of component.dispositions.entries()) {
      // The name once per component, so a type handled two ways reads as one entry with two rows.
      lines.push(`| ${index === 0 ? `\`${name}\`` : ``} | ${count} | ${escapeCell(disposition)} |`);
    }
  }
  return `${lines.join(`\n`)}\n`;
}

/** The whole of `component-coverage.md`. */
export function renderCoverage(report: ContentReport, screenCount: number): string {
  const components = report.components;
  const total = Object.values(components).reduce((sum, c) => sum + c.screens, 0);
  const counted = (category: ComponentCategory) =>
    Object.values(components).filter((c) => c.category === category).length;

  const summary = [
    `| Group | Types |`,
    `|---|---:|`,
    ...GROUPS.map((g) => `| ${g.heading} | ${counted(g.category)} |`),
    `| **Total** | **${Object.keys(components).length}** |`,
  ].join(`\n`);

  const unhandled = Object.entries(report.unhandledInline).sort((a, b) => b[1] - a[1]);
  const unhandledTable =
    unhandled.length === 0
      ? `_None._\n`
      : `${[`| Construct | Occurrences |`, `|---|---:|`, ...unhandled.map(([k, n]) => `| ${escapeCell(k)} | ${n} |`)].join(`\n`)}\n`;

  return (
    `<!-- GENERATED by \`make transpile\`. Do not edit: change codemod/components.ts and regenerate. -->\n\n` +
    `# Component coverage\n\n` +
    `Every content component type Direct File's flow declares, and what this port does with it.\n` +
    `Written from the same pass that emits the flow, over ${screenCount} screens and ` +
    `${total} content declarations.\n\n` +
    `An unmapped type is not a row here — \`ComponentMapper.blocks\` throws on it, naming the type ` +
    `and the screen, and the emit fails. So this file is a list of decisions, and every one of them ` +
    `is in \`codemod/components.ts\`.\n\n` +
    `${summary}\n\n` +
    GROUPS.map(
      (g) => `## ${g.heading}\n\n${g.blurb}\n\n${table(components, g.category)}`
    ).join(`\n`) +
    `\n## Inline constructs with no shape in the IR\n\n` +
    `Markup met inside an authored string that the inline IR has no node for. Each one is dropped to ` +
    `its text, so the words survive and the markup does not — a link stops being a link, a nested ` +
    `list stops being a list. Counted rather than silenced, because the number is the argument for ` +
    `adding a node.\n\n` +
    `${unhandledTable}\n` +
    `Enum and multi-enum option labels whose markup had to be flattened to plain text, because an ` +
    `\`<option>\` carries a string: **${report.flattenedOptionLabels}**.\n`
  );
}
