#!/usr/bin/env bash
#
# perf-baseline.sh — build the pre-plan artifacts that `perf.mjs --stage site,explorer` measures against.
#
# Stages 1 and 2 can be A/B'd by swapping a file under a running server. The rest cannot: Stage 3
# inlines nav templates into generated HTML, Stage 4 changes the library the site is generated by,
# and Stage 5 changes both the vendored bundle and the shape of the data on disk. Measuring "before
# the plan" therefore means building the site and the graph the way they were built before the plan,
# which is what this does.
#
# It touches exactly one thing outside its own scratch directory: ~/.ivy2/local, where form-builder
# publishes 0.1.0-SNAPSHOT. Both commits publish the same coordinates, so the baseline build has to
# borrow the cache — and step 5 hands it back. If this script is interrupted between steps 3 and 5,
# re-publish before building anything else:  cd ~/form-builder && sbt publishLocal
#
# Usage:  scripts/perf-baseline.sh [<output dir>]      (default: $TMPDIR/fbx-perf-baseline)
#
set -euo pipefail

OUT=${1:-${TMPDIR:-/tmp}/fbx-perf-baseline}
EXAMPLES=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PARENT=$(dirname "$EXAMPLES")
TAXPERT=${TAXPERT_DIR:-$PARENT/taxpert}
FORM_BUILDER=${FORM_BUILDER_DIR:-$PARENT/form-builder}
FACT_GRAPH=${FACT_GRAPH_DIR:-$PARENT/fact-graph}
APP=${APP:-direct-file}

# The plan is committed in two of the three repositories and uncommitted in this one, so "before" is
# a different ref in each. Same rule perf.mjs's baselineRef() uses, so the two cannot disagree.
baseline_ref () {
  case "$(git -C "$1" log -1 --format=%s)" in
    *[Pp]erf*) echo "HEAD^" ;;
    *) echo "HEAD" ;;
  esac
}

echo "==> baseline refs: examples $(baseline_ref "$EXAMPLES")  taxpert $(baseline_ref "$TAXPERT")  form-builder $(baseline_ref "$FORM_BUILDER")"
mkdir -p "$OUT"

# The worktrees are laid out as siblings under $OUT because that is what the checkouts expect of one
# another: direct-file resolves taxpert as `file:../../taxpert/packages/ui` and the Fact Graph
# bundle as `../../fact-graph`, both relative to the app. fact-graph is unchanged by the plan, so it
# is a symlink to the real one rather than a fourth build.
for repo in "$EXAMPLES:form-builder-examples" "$TAXPERT:taxpert" "$FORM_BUILDER:form-builder"; do
  src=${repo%%:*}; name=${repo##*:}
  if [ ! -d "$OUT/$name" ]; then
    git -C "$src" worktree add --detach "$OUT/$name" "$(baseline_ref "$src")"
  else
    echo "==> $OUT/$name exists; leaving it alone"
  fi
done
ln -sfn "$FACT_GRAPH" "$OUT/fact-graph"

DF=$OUT/form-builder-examples/$APP

echo "==> 1/5  node dependencies for the baseline app"
(cd "$DF" && npm install --no-audit --no-fund >/dev/null)

echo "==> 2/5  vendored USWDS and lint tooling"
# Pinned (@uswds/uswds 3.13.0) and untouched by the plan: copied from the working checkout rather
# than reinstalled, because a second resolve of the same pin is minutes for no difference.
[ -d "$DF/src/main/resources/$APP/node_modules" ] || \
  cp -R "$EXAMPLES/$APP/src/main/resources/$APP/node_modules" "$DF/src/main/resources/$APP/node_modules"

echo "==> 3/5  publishing form-builder @ baseline into the Ivy cache"
(cd "$OUT/form-builder" && sbt -batch publishLocal >/dev/null)

echo "==> 4/5  generating the baseline site"
# The app's own FLAGS, read from the baseline Makefile rather than repeated here: if the baseline
# built a different site from the one we compare it against, the comparison is of two sites.
FLAGS=$(sed -n 's/^FLAGS := //p' "$DF/Makefile")
echo "        flags: $FLAGS"
(cd "$DF" && make copy-fg copy-shared-ui copy-uswds >/dev/null && sbt -batch "run $FLAGS" 2>&1 | tail -3)
echo "        $(find "$DF/out" -name '*.html' | wc -l | tr -d ' ') pages"

echo "==> 5/5  restoring the Ivy cache to the working tree's form-builder"
(cd "$FORM_BUILDER" && sbt -batch publishLocal >/dev/null)

echo "==> baseline Fact Explorer: the graph as the baseline generator wrote it"
mkdir -p "$OUT/apps" && ln -sfn "$DF" "$OUT/apps/$APP"
(cd "$OUT/taxpert" && npm install --no-audit --no-fund >/dev/null)
(cd "$OUT/taxpert/packages/fact-explorer" && FORM_BUILDER_APPS_DIR=$OUT/apps npm run make-fgm 2>&1 | tail -3)

echo
echo "==> done. Measure it with:"
echo "    node scripts/perf.mjs --stage site,explorer --apps $APP --baseline $OUT"
