#!/usr/bin/env node
//
// perf.mjs — the measurement harness behind the performance audit and its staged plan.
//
// The audit's stages each claim a number. This runs the claim: it measures the same thing twice,
// once against the code as committed at HEAD and once against the working tree, and prints the
// pair. "How much faster" is a ratio or it is an anecdote, so nothing here reports a single figure.
//
//   Stage 1 (DF-3, DF-4, DF-8) — transport. Both sides are throwaway nginx containers started from
//   the app's *already built* runtime image with only /etc/nginx/conf.d/default.conf swapped, so the
//   two sides serve byte-identical files and differ in exactly the thing the stage changed. No sbt
//   run, no image rebuild, nothing written to the repo.
//
//   Two web roots exist and they are not the same site. `--root image` (the default) serves what is
//   baked into the runtime image: the product, built with no developer flags, ~72 subresources.
//   `--root volume` serves the named volume the running stack actually mounts over that path
//   (direct-file_app-out and friends), which the dev overlay's watcher fills with an --auditMode
//   --allScreens --authorMode build — ~148 subresources, and the site the audit's own numbers were
//   taken against. Both are worth knowing; neither is a substitute for the other.
//
//   `site` and `explorer` — the whole plan, end to end. Stages 1 and 2 each isolate one change;
//   these two answer the different question of what a user gets now versus before any of it landed.
//   They need a baseline that is a *built artifact*, not a file swap, because Stage 3 inlines nav
//   templates into generated HTML, Stage 4 changes a library the site is generated by, and Stage 5
//   changes both the vendored bundle and the shape of the data on disk — none of which a running
//   server can be talked into by rewriting a source file. `scripts/perf-baseline.sh` builds that
//   artifact; this script only measures it, and refuses to guess if it is missing.
//
//     site      — the generated Direct File site, pre-plan vs now. Two throwaway nginx containers
//                 from the same runtime image, each with its own nginx.conf and its own web root
//                 bind-mounted over /usr/share/nginx/html. Covers Stage 1 (transport), Stage 3 (the
//                 nav race), Stage 4 (paint before the graph) and Stage 5's TX-3, because all four
//                 land on the same pages.
//     explorer  — Fact Explorer, pre-plan vs now. Two Vite dev servers, each serving its own
//                 checkout and its own generated data. Covers Stage 2 and Stage 5's FX-3/6/7.
//
//   The three repositories are at different points relative to the plan — taxpert and form-builder
//   have committed it, this one has not — so "before" is not one ref. baselineRef() resolves each
//   repo's own: HEAD^ where HEAD is the commit that landed the work, HEAD otherwise. Both sides are
//   printed in the report, because a baseline you cannot name is not a baseline.
//
//   Stage 2 (FX-1, FX-2, FX-4, FX-5) — the Fact Explorer canvas. The dev stack bind-mounts
//   packages/fact-explorer into the Vite container (see taxpert/docker-compose.override.yml), so the
//   baseline side is produced by writing HEAD's copy of the three changed files over the working
//   tree, measuring, and putting the working tree back. That is a real edit to your checkout for the
//   duration of the run: it is guarded by a save-and-verify (contents hashed before, restored and
//   re-hashed after) and by handlers on SIGINT/SIGTERM/uncaughtException, and --no-ab skips it
//   entirely and measures only the working tree.
//
// Preconditions: the full stack is up (`make run-all-docker` here, `make up` in taxpert) and the
// four runtime images exist. Playwright comes from direct-file/node_modules — the smoke test's
// dependency, reused rather than re-declared.
//
// Usage:
//   node scripts/perf.mjs                        # both file-swap stages, both sides
//   node scripts/perf.mjs --stage 1              # one stage
//   scripts/perf-baseline.sh                     # build the pre-plan artifacts (once, ~5 min)
//   node scripts/perf.mjs --stage site,explorer --apps direct-file   # the whole plan, end to end
//   node scripts/perf.mjs --apps direct-file,twe # narrow, like the Makefile's APPS=
//   node scripts/perf.mjs --root volume          # measure the running stack's site, not the image
//   node scripts/perf.mjs --no-ab                # working tree only, no HEAD side
//   node scripts/perf.mjs --json out.json        # machine-readable alongside the report
//
// Timings are loopback and one machine: read the ratios, not the milliseconds. The `cable` profile
// below exists because loopback flatters DF-3 — it moves 12 MB in about a second, which is not what
// that finding is about.

import { execFile as execFileCb, execFileSync, spawn } from 'node:child_process'
import { promisify } from 'node:util'
import { readFileSync, writeFileSync, existsSync, mkdirSync, mkdtempSync, statSync, readdirSync, rmSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const execFile = promisify(execFileCb)
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
// Where perf-baseline.sh puts the pre-plan artifacts. Overridable with --baseline; deliberately
// outside the repo, for the same reason scratch() is.
const DEFAULT_BASELINE = process.env.PERF_BASELINE ?? path.join(tmpdir(), 'fbx-perf-baseline')
const TAXPERT = process.env.TAXPERT_DIR ?? path.join(path.dirname(ROOT), 'taxpert')
const EXPLORER = process.env.EXPLORER_URL ?? 'http://localhost:5180'

// Playwright is a devDependency of direct-file (`make smoke`), not of this repo's root, which has no
// package.json at all. Importing it by path keeps that true.
const playwright = (await import(pathToFileURL(path.join(ROOT, 'direct-file/node_modules/playwright/index.js')).href)).default
const { chromium } = playwright

// ---- what we measure ---------------------------------------------------------------------------

// port/image identify the *running* stack; base and explorer are the two ids AGENTS.md warns are
// independent of the directory name (credit-assistant is the case where all three differ).
const APPS = [
  { dir: 'direct-file', base: '/app/direct-file', port: 3008, explorer: 'direct-file' },
  { dir: 'credit-assistant', base: '/app/eitc', port: 3003, explorer: 'credit-assistant' },
  { dir: 'benefits-enrollment', base: '/app/benefits', port: 3006, explorer: 'benefits-enrollment' },
  { dir: 'tax-withholding-estimator', base: '/app/tax-withholding-estimator', port: 3000, explorer: 'twe' }
]

// Stage 2 rewrites these three and nothing else; the baseline side is HEAD's copy of exactly this
// list. Adding a file to the stage means adding it here or the baseline is not the baseline.
const STAGE2_FILES = [
  'packages/fact-explorer/src/canvas/FactExplorer.jsx',
  'packages/fact-explorer/src/canvas/controls/DisplayOptions.jsx',
  'packages/fact-explorer/src/model/load.js'
]

// Loopback moves 10 MB in about a second, which is not what DF-3 is about. `cable` is a plain
// consumer link — the demo that is not on the host machine, per DF-3's own wording.
const NET_PROFILES = [
  { name: 'loopback', latency: 0, down: -1, up: -1 },
  { name: 'cable-20Mb', latency: 40, down: 20e6 / 8, up: 5e6 / 8 }
]

const args = parseArgs(process.argv.slice(2))
const apps = APPS.filter((a) => !args.apps || args.apps.includes(a.dir) || args.apps.includes(a.explorer))
if (!apps.length) fail(`--apps matched nothing. Known: ${APPS.map((a) => a.dir).join(', ')}`)

const results = {
  measuredAt: new Date().toISOString(),
  head: gitRev(ROOT),
  taxpertHead: gitRev(TAXPERT),
  baselines: { examples: baselineRef(ROOT), taxpert: baselineRef(TAXPERT), baselineDir: args.baseline },
  stage1: null,
  stage2: null,
  site: null,
  explorer: null
}

if (args.stages.includes(1)) results.stage1 = await stage1()
if (args.stages.includes(2)) results.stage2 = await stage2()
if (args.stages.includes('site')) results.site = await stageSite()
if (args.stages.includes('explorer')) results.explorer = await stageExplorer()

// Written before the report, not after: the numbers cost minutes to collect and a formatting bug
// should not be able to throw them away.
if (args.json) {
  mkdirSync(path.dirname(path.resolve(args.json)), { recursive: true })
  writeFileSync(args.json, JSON.stringify(results, null, 2))
}
report(results)
if (args.json) console.log(`json: ${path.resolve(args.json)}\n`)

// ---- Stage 1 -----------------------------------------------------------------------------------

async function stage1 () {
  const out = { name: 'Transport hygiene', findings: ['DF-3', 'DF-4', 'DF-8'], apps: [] }
  const browser = await chromium.launch()
  try {
    for (const app of apps) {
      const image = await imageBehind(app)
      if (!image) { out.apps.push({ app: app.dir, error: `no running container publishing :${app.port}` }); continue }
      console.error(`  stage 1 · ${app.dir} · image ${image}`)

      const volume = args.root === 'volume' ? await volumeBehind(app) : null
      if (args.root === 'volume' && !volume) { out.apps.push({ app: app.dir, error: `:${app.port} mounts no volume over the web root` }); continue }
      const sides = {}
      let entry = null
      let assets = null
      let sourceMap = null

      for (const side of args.sides) {
        const conf = side === 'before'
          ? gitShow(ROOT, `HEAD:${app.dir}/nginx.conf`)
          : readFileSync(path.join(ROOT, app.dir, 'nginx.conf'), 'utf8')
        const server = await startNginx(image, conf, `${app.dir}-${side}`, volume)
        try {
          const origin = `http://127.0.0.1:${server.port}`
          // Discovered from the server we are about to measure, not from the live stack: with
          // --root image and --root volume serving different builds, an entry path or an engine
          // filename read from :3008 can simply not exist in the thing under test.
          entry ??= await resolveEntry(`${origin}${app.base}/`)
          assets ??= await criticalPath(server, app, origin, entry)
          sides[side] = {
            assets: await probeAssets(origin, assets),
            page: await loadPage(browser, origin + entry)
          }
          // While a server is up, because DF-8 is about the web root that is actually being served
          // and --root volume serves one the image has no say over.
          sourceMap ??= await sourceMapCheck(app, image, server)
        } finally {
          await server.stop()
        }
      }

      out.apps.push({
        app: app.dir,
        image,
        root: args.root,
        entry,
        sides,
        // DF-8 is not a header, so the A/B above cannot see it: both sides run the same image. What
        // it is, is a file that either is or is not in the web root being served.
        sourceMap
      })
    }
  } finally {
    await browser.close()
  }
  return out
}

// The image is read off the running container rather than guessed from the directory name, because
// the compose project name is whatever directory you brought the stack up from — `taxpert-*` images
// exist for the same apps, built from taxpert's own compose.
async function imageBehind (app) {
  const { stdout } = await execFile('docker', ['ps', '--filter', `publish=${app.port}`, '--format', '{{.Image}}'])
  return stdout.split('\n').map((s) => s.trim()).filter(Boolean).find((s) => !s.endsWith('-watch')) ?? null
}

// The compose stacks mount a named volume over /usr/share/nginx/html so the watcher can rewrite the
// site without rebuilding. That volume is seeded from the image the first time it is created and
// never again, so it can be arbitrarily older than the image — which is exactly why the two roots
// are reported separately rather than averaged into one "the app".
async function volumeBehind (app) {
  const { stdout } = await execFile('docker', ['ps', '--filter', `publish=${app.port}`, '--format', '{{.Names}}'])
  const name = stdout.split('\n').map((s) => s.trim()).filter(Boolean).find((s) => !s.endsWith('-watch-1'))
  if (!name) return null
  const { stdout: mounts } = await execFile('docker', ['inspect', name, '--format', '{{json .Mounts}}'])
  return JSON.parse(mounts).find((m) => m.Destination === '/usr/share/nginx/html' && m.Type === 'volume')?.Name ?? null
}

// `mount` is one of: nothing (serve what the image baked in), {volume} (the named volume the
// running stack mounts), or {dir} (a host directory — how the `site` stage serves a web root that
// was built somewhere else entirely).
async function startNginx (image, conf, tag, mount) {
  const volume = typeof mount === 'string' ? mount : mount?.volume
  const dir = mount?.dir
  const name = `fbx-perf-${tag}-${process.pid}`
  const confPath = path.join(scratch(), `${name}.conf`)
  writeFileSync(confPath, conf)
  await execFile('docker', ['rm', '-f', name]).catch(() => {})
  // Port 0 lets the kernel choose: this runs beside the live stack, and hard-coding a port is how a
  // measurement harness becomes the reason `make up` fails.
  await execFile('docker', ['run', '-d', '--rm', '--name', name,
    '-p', '127.0.0.1:0:80', '-v', `${confPath}:/etc/nginx/conf.d/default.conf:ro`,
    ...(volume ? ['-v', `${volume}:/usr/share/nginx/html:ro`] : []),
    ...(dir ? ['-v', `${dir}:/usr/share/nginx/html:ro`] : []), image])
  const { stdout } = await execFile('docker', ['port', name, '80'])
  const port = Number(stdout.trim().split('\n')[0].split(':').pop())
  for (let i = 0; i < 100; i++) {
    const code = await curl(`http://127.0.0.1:${port}/`, ['-o', '/dev/null', '-w', '%{http_code}']).catch(() => '')
    if (code && code !== '000') break
    await sleep(100)
  }
  return { name, port, stop: () => execFile('docker', ['rm', '-f', name]).catch(() => {}) }
}

// `/` on direct-file is a meta-refresh stub, so measuring it measures 517 bytes of nothing. Follow
// the stub to the page a user actually lands on; the other three serve the real page at `/`.
async function resolveEntry (url) {
  const body = await curl(url)
  const m = body.match(/http-equiv=["']refresh["'][^>]*url=([^"'>]+)/i)
  return m ? m[1].trim() : new URL(url).pathname
}

// The engine bundle is never named in the page: it arrives four levels down an import chain, so
// there is nothing in the HTML to match on. Ask the web root what it is called instead — the version
// in the filename moves with fact-graph, and hard-coding 3.1.0 here would quietly drop the largest
// asset in the audit from the largest number in this report.
async function criticalPath (server, app, origin, entry) {
  const { stdout } = await execFile('docker', ['exec', server.name, 'sh', '-c',
    `ls /usr/share/nginx/html${app.base}/resources/vendor/fact-graph/*.js 2>/dev/null | head -1`])
  const engine = stdout.trim()
  return [
    { label: 'entry document', url: entry },
    engine && { label: 'engine bundle', url: engine.replace('/usr/share/nginx/html', '') },
    { label: 'fact dictionary', url: `${app.base}/resources/fact-dictionary.xml` },
    { label: 'flow manifest', url: `${app.base}/resources/flow-manifest.json` },
    { label: 'vendored nav template', url: `${app.base}/resources/vendor/taxpert/global-nav/templates/global-nav.html` }
  ].filter(Boolean)
}

// curl rather than fetch: undici transparently decodes gzip and drops the headers that prove it did,
// which is the one thing this probe exists to see. Without --compressed curl leaves the body encoded,
// so size_download is what actually crossed the wire.
async function probeAssets (origin, assets) {
  const rows = []
  for (const a of assets) {
    const raw = await curl(origin + a.url, ['-o', '/dev/null', '-D', '-', '-H', 'Accept-Encoding: gzip, br',
      '-w', '\n__W %{size_download} %{http_code}\n'])
    const h = Object.fromEntries(raw.split('\n')
      .filter((l) => l.includes(':'))
      .map((l) => [l.slice(0, l.indexOf(':')).trim().toLowerCase(), l.slice(l.indexOf(':') + 1).trim()]))
    const [, wire, code] = raw.match(/__W (\d+) (\d+)/) ?? []
    rows.push({
      ...a,
      status: Number(code),
      wireBytes: Number(wire),
      encoding: h['content-encoding'] ?? null,
      cacheControl: h['cache-control'] ?? null,
      etag: Boolean(h.etag)
    })
  }
  return rows
}

// One cold visit per network profile. There is deliberately no second, warm visit: Chromium's
// in-process memory cache serves a same-context revisit whatever the headers say, so a warm pass
// measures the browser rather than the change, and reports the same number for both sides.
//
// DF-4 is therefore counted, not timed — from the response headers of every subresource the page
// actually pulls. "Reusable" is what a browser will serve on a later visit without asking nginx
// first; every other same-origin response is a conditional request, and a round trip, on every
// navigation of a 758-page site.
async function loadPage (browser, url) {
  const out = {}
  for (const profile of NET_PROFILES) {
    const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    const page = await ctx.newPage()
    const t = installNetworkTally(await ctx.newCDPSession(page), new URL(url).origin)
    if (profile.down > 0) {
      await t.cdp.send('Network.emulateNetworkConditions',
        { offline: false, latency: profile.latency, downloadThroughput: profile.down, uploadThroughput: profile.up })
    }
    out[profile.name] = await navigate(page, t, url)
    await ctx.close()
  }
  return out
}

// Groups exist because "requests on the page" is the number TX-3 moves and it is not the number
// Stage 1 moves. Attributing bytes to a group needs the URL at loadingFinished, which only carries
// a requestId — hence the map.
// Declared as a function for the reason the file keeps running into: everything below the stage
// dispatch is reached before its own const initialisers have run.
function groupNames () { return ['taxpert-js', 'taxpert-css', 'taxpert-templates', 'fgm-data', 'other'] }
function groupOf (url) {
  if (/\/vendor\/taxpert\//.test(url)) {
    if (/\/templates\/.*\.html/.test(url)) return 'taxpert-templates'
    if (/\.css(\?|$)/.test(url)) return 'taxpert-css'
    return 'taxpert-js'
  }
  if (/\/data\/.*\.json(\?|$)/.test(url)) return 'fgm-data'
  return 'other'
}

function installNetworkTally (cdp, origin) {
  const blank = () => Object.fromEntries(groupNames().map((g) => [g, { n: 0, bytes: 0 }]))
  const t = { cdp, requests: 0, fromCache: 0, bytes: 0, status: {}, cache: { reusable: 0, revalidate: 0, unset: 0, sameOrigin: 0 }, groups: blank(), urls: new Map() }
  cdp.send('Network.enable')
  cdp.on('Network.requestWillBeSent', (e) => { t.requests++; t.urls.set(e.requestId, e.request.url); t.groups[groupOf(e.request.url)].n++ })
  // Backed out again when the browser answers it from its own memory cache. Without this the group
  // counts are not "requests over the network": an audit-mode page mounts a second copy of itself
  // once the workspace boots, and on loopback that lands inside networkidle and doubles every
  // count while costing nothing on the wire — a comparison of two browsers, not of two builds.
  cdp.on('Network.requestServedFromCache', (e) => {
    t.fromCache++
    const url = t.urls.get(e.requestId)
    if (url) t.groups[groupOf(url)].n--
  })
  cdp.on('Network.loadingFinished', (e) => {
    t.bytes += e.encodedDataLength
    const url = t.urls.get(e.requestId)
    if (url) t.groups[groupOf(url)].bytes += e.encodedDataLength
  })
  cdp.on('Network.responseReceived', (e) => {
    t.status[e.response.status] = (t.status[e.response.status] ?? 0) + 1
    if (!e.response.url.startsWith(origin)) return
    t.cache.sameOrigin++
    const cc = header(e.response.headers, 'cache-control')
    if (!cc) t.cache.unset++
    else if (/immutable/i.test(cc) || Number(cc.match(/max-age=(\d+)/i)?.[1] ?? 0) >= 86400) t.cache.reusable++
    else t.cache.revalidate++
  })
  t.reset = () => { t.requests = 0; t.fromCache = 0; t.bytes = 0; t.status = {}; t.cache = { reusable: 0, revalidate: 0, unset: 0, sameOrigin: 0 }; t.groups = blank() }
  t.snapshot = () => ({ requests: t.requests, fromCache: t.fromCache, network: t.requests - t.fromCache, bytes: t.bytes, status: { ...t.status }, cache: { ...t.cache }, groups: structuredClone(t.groups) })
  return t
}

// CDP hands headers back with whatever casing the server used.
function header (headers, name) {
  return Object.entries(headers).find(([k]) => k.toLowerCase() === name)?.[1] ?? null
}

async function navigate (page, tally, url) {
  tally.reset()
  const t0 = Date.now()
  await page.goto(url, { waitUntil: 'load', timeout: 180000 })
  const loadMs = Date.now() - t0
  await page.waitForLoadState('networkidle', { timeout: 180000 }).catch(() => {})
  const settleMs = Date.now() - t0
  const nav = await page.evaluate(() => {
    const n = performance.getEntriesByType('navigation')[0]
    const fcp = performance.getEntriesByName('first-contentful-paint')[0]
    return { dcl: n ? Math.round(n.domContentLoadedEventEnd) : null, fcp: fcp ? Math.round(fcp.startTime) : null }
  })
  return { loadMs, settleMs, ...nav, ...tally.snapshot() }
}

async function sourceMapCheck (app, image, server) {
  const find = async (argv) => (await execFile('docker', argv)).stdout.split('\n').map((s) => s.trim()).filter(Boolean)
  const inImage = await find(['run', '--rm', '--entrypoint', 'sh', image, '-c', "find / -name '*.mjs.map' 2>/dev/null | head -5"])
  const served = await find(['exec', server.name, 'sh', '-c', "find /usr/share/nginx/html -name '*.mjs.map' 2>/dev/null | head -5"])
  const onDisk = [`${app.dir}/src/main/resources`, `${app.dir}/out`].flatMap((d) => findMap(path.join(ROOT, d)))
  return { inImage, served, bytes: onDisk.length ? statSize(onDisk[0]) : null, onDisk: onDisk.map((p) => path.relative(ROOT, p)) }
}

// ---- Stage 2 -----------------------------------------------------------------------------------

async function stage2 () {
  const out = { name: 'The Fact Explorer canvas', findings: ['FX-1', 'FX-2', 'FX-4', 'FX-5'], runs: [] }
  const browser = await chromium.launch()
  const restore = args.sides.includes('before') ? saveWorkingTree() : null
  try {
    for (const side of args.sides) {
      if (side === 'before') {
        for (const f of STAGE2_FILES) writeFileSync(path.join(TAXPERT, f), gitShow(TAXPERT, `HEAD:${f}`))
      } else if (restore) {
        restore.put()
      }
      await waitForVite(side)
      for (const app of apps) {
        for (const slice of await slicesFor(browser, app)) {
          console.error(`  stage 2 · ${side} · ${app.explorer} · ${slice.label}`)
          out.runs.push({ side, app: app.explorer, slice: slice.label, value: slice.value, ...await measureCanvas(browser, app, slice) })
        }
      }
    }
  } finally {
    if (restore) restore.put({ verify: true })
    await browser.close()
  }
  return out
}

// Save first, restore-and-verify after. If the hash does not match on the way back, say so loudly
// rather than exiting 0 on a checkout that has quietly lost the stage's work.
function saveWorkingTree () {
  const saved = STAGE2_FILES.map((f) => {
    const abs = path.join(TAXPERT, f)
    const body = readFileSync(abs, 'utf8')
    return { f, abs, body, sha: sha256(body) }
  })
  const copy = path.join(scratch(), 'stage2-working-tree.json')
  writeFileSync(copy, JSON.stringify(saved, null, 2))
  const put = ({ verify = false } = {}) => {
    for (const s of saved) {
      if (existsSync(s.abs) && sha256(readFileSync(s.abs, 'utf8')) === s.sha) continue
      writeFileSync(s.abs, s.body)
    }
    if (verify) {
      const bad = saved.filter((s) => sha256(readFileSync(s.abs, 'utf8')) !== s.sha)
      if (bad.length) {
        console.error(`\n!! working tree NOT restored: ${bad.map((b) => b.f).join(', ')}`)
        console.error(`!! the saved copies are in ${copy}`)
        process.exitCode = 1
      }
    }
  }
  for (const sig of ['SIGINT', 'SIGTERM']) process.once(sig, () => { put({ verify: true }); process.exit(130) })
  process.once('uncaughtException', (e) => { put({ verify: true }); throw e })
  return { put }
}

// The container polls the bind mount (VITE_USE_POLLING), so the swap lands within a second or two.
// Poll the transformed module Vite is actually serving rather than sleeping a guessed interval:
// `onlyRenderVisibleElements` appears in it on one side and not the other, which makes the wait
// self-verifying — if it times out, the side we are about to measure is not the side we asked for.
async function waitForVite (side) {
  const want = side === 'after'
  for (let i = 0; i < 120; i++) {
    const src = await curl(`${EXPLORER}/src/canvas/FactExplorer.jsx`).catch(() => '')
    if (src.includes('onlyRenderVisibleElements') === want) { await sleep(500); return }
    await sleep(500)
  }
  fail(`Vite is still serving the ${want ? 'HEAD' : 'working-tree'} FactExplorer.jsx after 60s — is ${EXPLORER} the dev stack?`)
}

// Every app's default slice, plus its full graph. The default is what opening the explorer costs;
// the full graph is the one the stage is about.
async function slicesFor (browser, app) {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } })
  try {
    await page.goto(`${EXPLORER}/fact-explorer/${app.explorer}`, { waitUntil: 'load', timeout: 180000 })
    await page.waitForFunction(() => document.querySelectorAll('#fe-scope option').length > 1, null, { timeout: 180000 })
    const opts = await page.$$eval('#fe-scope option', (els) => els.map((e) => ({ value: e.value, label: e.textContent.trim() })))
    const def = await page.$eval('#fe-scope', (e) => e.value)
    const picked = [{ value: null, label: `default · ${opts.find((o) => o.value === def)?.label ?? def}` }]
    const full = opts.find((o) => o.value === 'full')
    if (full) picked.push({ value: 'full', label: full.label })
    // direct-file's flowGates is the middle case: big enough to matter, below the threshold Stage 2
    // gates the minimap and edge animation on. It is the slice that shows the gate is not a cliff.
    const gates = opts.find((o) => o.value === 'file::flowGates.xml')
    if (gates && app.explorer === 'direct-file') picked.splice(1, 0, { value: gates.value, label: gates.label })
    return picked
  } finally {
    await page.close()
  }
}

async function measureCanvas (browser, app, slice) {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } })
  let mockRequests = 0
  page.on('request', (r) => { if (r.url().includes('form-builder-graph.mock.json')) mockRequests++ })
  try {
    await page.goto(`${EXPLORER}/fact-explorer/${app.explorer}`, { waitUntil: 'load', timeout: 180000 })
    await page.waitForSelector('#fe-scope', { timeout: 180000 })
    await page.waitForSelector('.react-flow__node', { timeout: 180000 })

    await page.evaluate(() => {
      window.__lt = { count: 0, total: 0, max: 0 }
      new PerformanceObserver((l) => {
        for (const e of l.getEntries()) { window.__lt.count++; window.__lt.total += e.duration; window.__lt.max = Math.max(window.__lt.max, e.duration) }
      }).observe({ entryTypes: ['longtask'] })
    })

    const t0 = Date.now()
    if (slice.value) await page.selectOption('#fe-scope', slice.value)
    // Settle is "the node count stopped changing", not a load event: the canvas keeps mounting long
    // after the fetch resolves, which is the thing being measured.
    let last = -1; let stable = 0
    while (Date.now() - t0 < 180000) {
      const n = await page.evaluate(() => document.querySelectorAll('.react-flow__node').length)
      if (n === last && n > 0) { if (++stable >= 3) break } else { stable = 0 }
      last = n
      await page.waitForTimeout(300)
    }
    const settleMs = Date.now() - t0

    const counts = await page.evaluate(() => ({
      rfNodes: document.querySelectorAll('.react-flow__node').length,
      rfEdges: document.querySelectorAll('.react-flow__edge').length,
      miniMapNodes: document.querySelectorAll('.react-flow__minimap-node').length,
      animatedEdges: document.querySelectorAll('.react-flow__edge.animated').length,
      domUnderViewport: document.querySelector('.react-flow__viewport')?.querySelectorAll('*').length ?? 0,
      blockingMs: Math.round(window.__lt.total),
      longTasks: window.__lt.count
    }))

    return { settleMs, ...counts, frames: await panFrames(page), mockRequests }
  } finally {
    await page.close()
  }
}

// The headline. Drag the pane and time the frames *during* the drag: an rAF loop awaited before the
// mouse moves measures an idle canvas, which is fast on both sides and says nothing.
async function panFrames (page) {
  const box = await (await page.$('.react-flow__pane')).boundingBox()
  const cx = box.x + box.width / 2
  const cy = box.y + box.height / 2
  await page.mouse.move(cx, cy)
  await page.mouse.down()
  await page.evaluate(() => {
    window.__raf = []
    let prev = performance.now()
    const tick = () => {
      const now = performance.now()
      window.__raf.push(now - prev)
      prev = now
      if (window.__rafOn) requestAnimationFrame(tick)
    }
    window.__rafOn = true
    requestAnimationFrame(tick)
  })
  for (let i = 0; i < 30; i++) await page.mouse.move(cx - i * 18, cy - i * 9)
  await page.mouse.up()
  return page.evaluate(() => {
    window.__rafOn = false
    const a = window.__raf.slice(2).sort((x, y) => x - y)
    if (!a.length) return { n: 0, p50: 0, p95: 0, max: 0 }
    return { n: a.length, p50: Math.round(a[Math.floor(a.length * 0.5)]), p95: Math.round(a[Math.floor(a.length * 0.95)]), max: Math.round(a.at(-1)) }
  })
}

// ---- the whole plan: the generated site ---------------------------------------------------------
//
// What a browser sees on a Direct File page before any of the plan landed, and now. Both sides are
// real builds — same flags, same 774 pages — served by the same nginx binary from the same image,
// so the only differences are the ones the plan made.

// Recorded in the page rather than derived from the trace, because both of these are about the
// moment something became true of the DOM, and neither has a Performance entry.
//
//   navReadyMs      Stage 3. The nav bar renders from templates the page now carries; before, from
//                   a fetch queued behind the flow runtime's boot. This is when the bar has markup.
//   contentReadyMs  Stage 4. The baseline ships <div id="page-content-wrapper" inert> behind a
//                   display:none, and flow-runtime.js clears both at the end of its boot; after the
//                   stage the wrapper is neither. So: the first frame at which the page is both
//                   visible and interactive, which on one side is parse time and on the other is
//                   parse time plus the whole engine boot.
// A function declaration, not a const: report() is not the only thing that runs above its own
// definitions in this file — the stage dispatch does too, and a const here is in the temporal dead
// zone when stageSite() reaches for it.
function instrumentScript () {
  return `(() => {
  const P = { longTasks: 0, blockingMs: 0, navReadyMs: null, contentReadyMs: null }
  window.__perf = P
  try {
    new PerformanceObserver((l) => {
      for (const e of l.getEntries()) { P.longTasks++; P.blockingMs += Math.max(0, e.duration - 50) }
    }).observe({ entryTypes: ['longtask'] })
  } catch (e) { /* no longtask support: the counters stay 0 rather than the run failing */ }
  const deadline = performance.now() + 120000
  const tick = () => {
    if (P.navReadyMs === null && document.querySelector('taxpert-global-nav .tgn-bar')) P.navReadyMs = performance.now()
    const w = document.getElementById('page-content-wrapper')
    if (P.contentReadyMs === null && w && !w.hasAttribute('inert') && w.getClientRects().length > 0) P.contentReadyMs = performance.now()
    // Stops as soon as both are known: an rAF loop left running for the whole measurement is a
    // sixty-times-a-second tax on the thing being measured.
    if ((P.navReadyMs !== null && P.contentReadyMs !== null) || performance.now() > deadline) return
    requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
})()`
}

async function stageSite () {
  const out = { name: 'The generated site, pre-plan vs now', findings: ['DF-3', 'DF-4', 'DF-8', 'TX-1', 'TX-2', 'DF-2', 'DF-6', 'TX-3'], apps: [] }
  const browser = await chromium.launch()
  try {
    for (const app of apps) {
      const roots = {
        before: path.join(args.baseline, 'form-builder-examples', app.dir, 'out'),
        after: path.join(ROOT, app.dir, 'out')
      }
      const missing = args.sides.filter((side) => !existsSync(roots[side]))
      if (missing.length) {
        out.apps.push({ app: app.dir, error: `no built site for "${missing.join(', ')}" (looked in ${missing.map((m) => roots[m]).join(', ')}) — run scripts/perf-baseline.sh` })
        continue
      }
      const image = await imageBehind(app)
      if (!image) { out.apps.push({ app: app.dir, error: `no running container publishing :${app.port}, and its nginx is what serves both sides` }); continue }

      const pages = pagesToMeasure(roots, app)
      console.error(`  site · ${app.dir} · image ${image} · ${pages.map((p) => p.label).join(', ')}`)
      const sides = {}
      let assets = null
      let entry = null

      for (const side of args.sides) {
        const conf = side === 'before'
          ? gitShow(ROOT, `${baselineRef(ROOT)}:${app.dir}/nginx.conf`)
          : readFileSync(path.join(ROOT, app.dir, 'nginx.conf'), 'utf8')
        const server = await startNginx(image, conf, `${app.dir}-plan-${side}`, { dir: roots[side] })
        try {
          const origin = `http://127.0.0.1:${server.port}`
          // direct-file's `/` is a meta-refresh stub; measuring it measures 517 bytes of nothing.
          entry ??= await resolveEntry(`${origin}${app.base}/`)
          assets ??= await criticalPath(server, app, origin, entry)
          const measured = {}
          for (const pg of pages) {
            console.error(`    ${side} · ${pg.label}`)
            measured[pg.label] = await loadPageDeep(browser, origin + (pg.label === 'entry' ? entry : pg.url))
          }
          sides[side] = { pages: measured, assets: await probeAssets(origin, assets) }
        } finally {
          await server.stop()
        }
      }
      out.apps.push({ app: app.dir, image, pages, sides })
    }
  } finally {
    await browser.close()
  }
  return out
}

// Three pages, and each is a different question. The entry is what a first visit costs; the
// heaviest topic page is what the flow costs at its worst; all-screens is the developer surface
// that loads the whole chrome at once. Ranked by generated size and intersected across the two
// sides, so the pair being compared is the same page on both — a page that exists on only one side
// would make the comparison a comparison of two different documents.
function pagesToMeasure (roots, app) {
  const rank = (root) => {
    const base = path.join(root, app.base.replace(/^\//, ''))
    if (!existsSync(base)) return []
    return readdirSync(base, { recursive: true, withFileTypes: true })
      .filter((d) => d.isFile() && d.name === 'index.html')
      .map((d) => {
        const abs = path.join(d.parentPath ?? d.path, d.name)
        return { url: `${app.base}/${path.relative(base, path.dirname(abs))}/`.replace(/\/+$/, '/'), size: statSize(abs) }
      })
      .filter((x) => !x.url.includes('/es/'))
      .sort((a, b) => b.size - a.size)
  }
  const after = rank(roots.after)
  const beforeUrls = new Set(rank(roots.before).map((x) => x.url))
  const common = after.filter((x) => beforeUrls.size === 0 || beforeUrls.has(x.url))
  const entry = `${app.base}/`
  const allScreens = common.find((x) => x.url.endsWith('/all-screens/'))
  const heaviest = common.find((x) => !x.url.endsWith('/all-screens/') && x.url !== entry)
  return [
    { label: 'entry', url: entry },
    heaviest && { label: 'heaviest flow page', url: heaviest.url, bytes: heaviest.size },
    allScreens && { label: 'all-screens', url: allScreens.url, bytes: allScreens.size }
  ].filter(Boolean)
}

async function loadPageDeep (browser, url) {
  const out = {}
  for (const profile of NET_PROFILES) {
    const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    await ctx.addInitScript(instrumentScript())
    const page = await ctx.newPage()
    const errors = []
    page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text().slice(0, 160)) })
    page.on('pageerror', (e) => errors.push(String(e.message).slice(0, 160)))
    const t = installNetworkTally(await ctx.newCDPSession(page), new URL(url).origin)
    if (profile.down > 0) {
      await t.cdp.send('Network.emulateNetworkConditions',
        { offline: false, latency: profile.latency, downloadThroughput: profile.down, uploadThroughput: profile.up })
    }
    const nav = await navigate(page, t, url)
    const marks = await page.evaluate(() => ({ ...window.__perf })).catch(() => ({}))
    out[profile.name] = { ...nav, ...marks, consoleErrors: errors.length, errorSample: [...new Set(errors)].slice(0, 3) }
    await ctx.close()
  }
  return out
}

// ---- the whole plan: Fact Explorer ---------------------------------------------------------------
//
// Two Vite dev servers, each serving its own checkout and its own generated data — which matters as
// much as the code: the baseline's graph is what the baseline's generator wrote (one pretty-printed
// file, no shards), and re-pointing one server at the other's data would measure neither side.

async function stageExplorer () {
  const out = { name: 'Fact Explorer, pre-plan vs now', findings: ['FX-1', 'FX-2', 'FX-3', 'FX-4', 'FX-5', 'FX-6', 'FX-7'], runs: [], transport: {} }
  const dirs = {
    before: path.join(args.baseline, 'taxpert/packages/fact-explorer'),
    after: path.join(TAXPERT, 'packages/fact-explorer')
  }
  const missing = args.sides.filter((side) => !existsSync(path.join(dirs[side], 'public/data/apps.json')))
  if (missing.length) return { ...out, error: `no generated data for "${missing.join(', ')}" — run scripts/perf-baseline.sh` }

  const browser = await chromium.launch()
  try {
    for (const side of args.sides) {
      const server = await startVite(dirs[side], `plan-${side}`)
      try {
        out.transport[side] = await probeGraphTransport(server.origin, apps)
        for (const app of apps) {
          console.error(`  explorer · ${side} · ${app.explorer}`)
          out.runs.push({ side, app: app.explorer, ...await measureExplorer(browser, server.origin, app) })
        }
      } finally {
        await server.stop()
      }
    }
  } finally {
    await browser.close()
  }
  return out
}

// FX-7 is a header, so it is asked for with curl rather than inferred from a page load: what the
// dev server does with Accept-Encoding, and whether a second visit is a 304 or a re-download.
async function probeGraphTransport (origin, list) {
  const rows = []
  for (const app of list) {
    const url = `${origin}/data/${app.explorer}/form-builder-graph.json`
    const raw = await curl(url, ['-o', '/dev/null', '-D', '-', '-H', 'Accept-Encoding: gzip', '-w', '\n__W %{size_download} %{http_code}\n'])
    const h = Object.fromEntries(raw.split('\n').filter((l) => l.includes(':')).map((l) => [l.slice(0, l.indexOf(':')).trim().toLowerCase(), l.slice(l.indexOf(':') + 1).trim()]))
    const [, wire, code] = raw.match(/__W (\d+) (\d+)/) ?? []
    let revalidated = null
    if (h.etag) {
      const second = await curl(url, ['-o', '/dev/null', '-D', '-', '-H', `If-None-Match: ${h.etag}`, '-w', '\n__W %{size_download} %{http_code}\n'])
      revalidated = Number(second.match(/__W \d+ (\d+)/)?.[1] ?? 0)
    }
    rows.push({ app: app.explorer, status: Number(code), wireBytes: Number(wire), encoding: h['content-encoding'] ?? null, cacheControl: h['cache-control'] ?? null, etag: h.etag ?? null, revalidatedStatus: revalidated })
  }
  return rows
}

async function startVite (dir, tag) {
  const port = 5190 + (tag.includes('before') ? 0 : 1)
  // A stale optimizer cache from a previous run would hide the very thing FX-6 changed, and the two
  // checkouts have different exports maps.
  rmSync(path.join(dir, 'node_modules/.vite'), { recursive: true, force: true })
  const child = spawn('npx', ['vite', '--port', String(port), '--strictPort', '--no-open', '--host', '127.0.0.1'],
    { cwd: dir, env: { ...process.env, VITE_FGM_SOURCE: 'real' }, stdio: ['ignore', 'pipe', 'pipe'] })
  const log = []
  child.stdout.on('data', (b) => log.push(String(b)))
  child.stderr.on('data', (b) => log.push(String(b)))
  const origin = `http://127.0.0.1:${port}`
  for (let i = 0; i < 300; i++) {
    const code = await curl(origin + '/', ['-o', '/dev/null', '-w', '%{http_code}']).catch(() => '')
    if (code === '200') return { origin, stop: async () => { child.kill('SIGTERM'); await sleep(500); child.kill('SIGKILL') } }
    if (child.exitCode !== null) fail(`vite in ${dir} exited ${child.exitCode}:\n${log.join('')}`)
    await sleep(200)
  }
  child.kill('SIGKILL')
  fail(`vite in ${dir} never answered on ${origin}:\n${log.join('')}`)
}

async function measureExplorer (browser, origin, app) {
  const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } })
  await ctx.addInitScript(instrumentScript())
  const page = await ctx.newPage()
  const t = installNetworkTally(await ctx.newCDPSession(page), origin)
  let wholeGraphFetches = 0
  page.on('request', (r) => { if (/\/data\/.*\/form-builder-graph\.json/.test(r.url())) wholeGraphFetches++ })
  try {
    t.reset()
    const t0 = Date.now()
    await page.goto(`${origin}/fact-explorer/${app.explorer}`, { waitUntil: 'commit', timeout: 300000 })
    await page.waitForSelector('.react-flow__node', { timeout: 300000 })
    const firstNodeMs = Date.now() - t0
    await settleCanvas(page, t0)
    const opening = { firstNodeMs, settleMs: Date.now() - t0, ...t.snapshot(), wholeGraphFetches, ...await canvasCounts(page) }
    const openingFrames = await panFrames(page)

    // The full graph: the one thing the sharding deliberately still supports, and the number that
    // says what it costs when you ask for it.
    let full = null
    let fullFrames = null
    const hasFull = await page.$$eval('#fe-scope option', (els) => els.some((e) => e.value === 'full'))
    if (hasFull) {
      t.reset()
      const t1 = Date.now()
      await page.selectOption('#fe-scope', 'full')
      await settleCanvas(page, t1)
      full = { settleMs: Date.now() - t1, ...t.snapshot(), ...await canvasCounts(page) }
      fullFrames = await panFrames(page)
    }
    return { opening: { ...opening, frames: openingFrames }, full: full && { ...full, frames: fullFrames } }
  } finally {
    await ctx.close()
  }
}

// "The node count stopped changing", not a load event — the same definition stage 2 uses, and for
// the same reason: the canvas keeps mounting long after the fetch resolves.
async function settleCanvas (page, t0) {
  let last = -1
  let stable = 0
  while (Date.now() - t0 < 300000) {
    const n = await page.evaluate(() => document.querySelectorAll('.react-flow__node').length)
    if (n === last && n > 0) { if (++stable >= 3) break } else { stable = 0 }
    last = n
    await page.waitForTimeout(300)
  }
}

function canvasCounts (page) {
  return page.evaluate(() => ({
    rfNodes: document.querySelectorAll('.react-flow__node').length,
    rfEdges: document.querySelectorAll('.react-flow__edge').length,
    miniMapNodes: document.querySelectorAll('.react-flow__minimap-node').length,
    domUnderViewport: document.querySelector('.react-flow__viewport')?.querySelectorAll('*').length ?? 0,
    blockingMs: Math.round(window.__perf?.blockingMs ?? 0),
    longTasks: window.__perf?.longTasks ?? 0
  }))
}

// The plan is committed in taxpert and form-builder and uncommitted here, so "before" is a different
// ref in each. The rule is mechanical and the resolved refs are printed: if the tip commit is the one
// that landed the work, the baseline is its parent; otherwise the baseline is the tip.
function baselineRef (repo) {
  try {
    const subject = execSync(repo, ['git', 'log', '-1', '--format=%s']).trim()
    return /perf|performance/i.test(subject) ? 'HEAD^' : 'HEAD'
  } catch { return 'HEAD' }
}

// ---- report ------------------------------------------------------------------------------------

function report (r) {
  const line = (s = '') => console.log(s)
  line()
  line('='.repeat(96))
  line(`form-builder-examples performance report · ${r.measuredAt}`)
  line(`  examples @ ${r.head}   taxpert @ ${r.taxpertHead}`)
  line(`  before = HEAD   after = working tree${args.sides.length === 1 ? `   (only "${args.sides[0]}" measured)` : ''}`)
  if (r.site || r.explorer) {
    line(`  whole-plan baselines: examples ${r.baselines.examples}, taxpert ${r.baselines.taxpert}   built into ${r.baselines.baselineDir}`)
  }
  line('='.repeat(96))

  if (r.stage1) {
    line()
    line(`Stage 1 — ${r.stage1.name}   ${r.stage1.findings.join(' ')}`)
    for (const a of r.stage1.apps) {
      line()
      line(`  ${a.app}`)
      if (a.error) { line(`    ${a.error}`); continue }
      const b = a.sides.before; const f = a.sides.after
      if (b && f) {
        const L = 34
        line(`    ${'critical path, gzip offered'.padEnd(L)} ${cmp(sum(b.assets, 'wireBytes'), sum(f.assets, 'wireBytes'), kb)}`)
        line(`    ${'whole page, bytes on the wire'.padEnd(L)} ${cmp(b.page.loopback.bytes, f.page.loopback.bytes, kb)}`)
        line(`    ${'whole page, requests'.padEnd(L)} ${b.page.loopback.network} → ${f.page.loopback.network}`)
        for (const p of NET_PROFILES) {
          line(`    ${`time to settle, ${p.name}`.padEnd(L)} ${cmp(b.page[p.name].settleMs, f.page[p.name].settleMs, ms)}`)
        }
        for (const p of NET_PROFILES) {
          line(`    ${`first contentful paint, ${p.name}`.padEnd(L)} ${cmp(b.page[p.name].fcp, f.page[p.name].fcp, ms)}`)
        }
        line(`    ${'compressed responses'.padEnd(L)} ${b.assets.filter((x) => x.encoding).length} → ${f.assets.filter((x) => x.encoding).length} of ${f.assets.length} probed`)
        const bc = b.page.loopback.cache; const fc = f.page.loopback.cache
        line(`    ${'reusable on a repeat visit'.padEnd(L)} ${bc.reusable} → ${fc.reusable} of ${fc.sameOrigin} responses`)
        line(`    ${'…so round trips avoided per page'.padEnd(L)} ${bc.reusable} → ${fc.reusable}` +
             `   (${fc.revalidate} still revalidate, ${fc.unset} unset)`)
      }
      const side = f ?? b
      if (side) {
        line()
        line(`    ${'asset'.padEnd(24)} ${'before'.padStart(11)} ${'after'.padStart(11)}  enc   Cache-Control`)
        for (let i = 0; i < side.assets.length; i++) {
          const ba = b?.assets[i]; const fa = f?.assets[i]
          line(`    ${side.assets[i].label.padEnd(24)} ${(ba ? kb(ba.wireBytes) : '-').padStart(11)} ${(fa ? kb(fa.wireBytes) : '-').padStart(11)}` +
               `  ${(fa?.encoding ?? '-').padEnd(5)} ${fa?.cacheControl ?? '-'}`)
        }
      }
      line()
      const sm = a.sourceMap
      line(`    DF-8 source map · image ${sm.inImage.length ? 'PRESENT' : 'absent'}` +
           ` · served root (${a.root}) ${sm.served.length ? 'PRESENT' : 'absent'}` +
           `${sm.bytes ? `   (${kb(sm.bytes)})` : ''}`)
    }
  }

  if (r.site) reportSite(r.site, line)
  if (r.explorer) reportExplorer(r.explorer, line)

  if (r.stage2) {
    line()
    line(`Stage 2 — ${r.stage2.name}   ${r.stage2.findings.join(' ')}`)
    line()
    const key = (x) => `${x.app}|${x.slice}`
    const before = new Map(r.stage2.runs.filter((x) => x.side === 'before').map((x) => [key(x), x]))
    const after = new Map(r.stage2.runs.filter((x) => x.side === 'after').map((x) => [key(x), x]))
    const seen = [...new Set(r.stage2.runs.map(key))]
    line(`    ${'app · slice'.padEnd(46)} ${'pan frame p50'.padStart(20)} ${'nodes in DOM'.padStart(18)} ${'DOM under canvas'.padStart(20)}`)
    for (const k of seen) {
      const b = before.get(k); const f = after.get(k)
      const s = f ?? b
      line(`    ${`${s.app} · ${s.slice}`.slice(0, 46).padEnd(46)} ${pair(b?.frames.p50, f?.frames.p50, ms).padStart(20)}` +
           ` ${pair(b?.rfNodes, f?.rfNodes, (n) => `${n}`).padStart(18)} ${pair(b?.domUnderViewport, f?.domUnderViewport, (n) => `${n}`).padStart(20)}`)
    }
    line()
    line(`    ${'app · slice'.padEnd(46)} ${'settle'.padStart(20)} ${'blocking'.padStart(18)} ${'minimap nodes'.padStart(20)}`)
    for (const k of seen) {
      const b = before.get(k); const f = after.get(k)
      const s = f ?? b
      line(`    ${`${s.app} · ${s.slice}`.slice(0, 46).padEnd(46)} ${pair(b?.settleMs, f?.settleMs, ms).padStart(20)}` +
           ` ${pair(b?.blockingMs, f?.blockingMs, ms).padStart(18)} ${pair(b?.miniMapNodes, f?.miniMapNodes, (n) => `${n}`).padStart(20)}`)
    }
    const mock = { before: sumBy(before, 'mockRequests'), after: sumBy(after, 'mockRequests') }
    line()
    line(`    FX-4 mock-fixture requests in real mode: ${mock.before} → ${mock.after}`)
  }
  line()
}

function reportSite (site, line) {
  line()
  line(`The generated site — pre-plan vs now   ${site.findings.join(' ')}`)
  for (const a of site.apps) {
    line()
    line(`  ${a.app}`)
    if (a.error) { line(`    ${a.error}`); continue }
    const b = a.sides.before
    const f = a.sides.after
    for (const pg of a.pages) {
      const bp = b?.pages[pg.label]
      const fp = f?.pages[pg.label]
      if (!bp && !fp) continue
      line()
      line(`    ${pg.label}${pg.bytes ? `  (${kb(pg.bytes)} of HTML)` : ''}`)
      const L = 36
      for (const prof of NET_PROFILES) {
        const x = bp?.[prof.name]
        const y = fp?.[prof.name]
        if (!x && !y) continue
        line(`      ── ${prof.name}`)
        line(`      ${'bytes on the wire'.padEnd(L)} ${cmp(x.bytes, y.bytes, kb)}`)
        line(`      ${'requests over the network'.padEnd(L)} ${x.network} → ${y.network}`)
        line(`      ${'first contentful paint'.padEnd(L)} ${cmp(x.fcp, y.fcp, ms)}`)
        line(`      ${'content readable and interactive'.padEnd(L)} ${cmp(x.contentReadyMs, y.contentReadyMs, ms)}`)
        line(`      ${'nav bar has markup'.padEnd(L)} ${cmp(x.navReadyMs, y.navReadyMs, ms)}`)
        line(`      ${'load event'.padEnd(L)} ${cmp(x.loadMs, y.loadMs, ms)}`)
        line(`      ${'quiet (networkidle)'.padEnd(L)} ${cmp(x.settleMs, y.settleMs, ms)}`)
        line(`      ${'main thread blocked'.padEnd(L)} ${cmp(x.blockingMs, y.blockingMs, ms)}`)
      }
      const x = bp?.loopback
      const y = fp?.loopback
      if (x && y) {
        line(`      ${'taxpert requests (js/css/templates)'.padEnd(38)} ${grp(x.groups)} → ${grp(y.groups)}`)
        line(`      ${'taxpert bytes'.padEnd(38)} ${cmp(grpBytes(x.groups), grpBytes(y.groups), kb)}`)
        line(`      ${'reusable on a repeat visit'.padEnd(38)} ${x.cache.reusable} → ${y.cache.reusable} of ${y.cache.sameOrigin} same-origin`)
        line(`      ${'console errors'.padEnd(38)} ${x.consoleErrors} → ${y.consoleErrors}${y.errorSample?.length ? `   (${y.errorSample[0]})` : ''}`)
      }
    }
    if (b && f) {
      line()
      line(`    ${'critical-path asset'.padEnd(24)} ${'before'.padStart(11)} ${'after'.padStart(11)}  enc   Cache-Control`)
      for (let i = 0; i < f.assets.length; i++) {
        const ba = b.assets[i]
        const fa = f.assets[i]
        line(`    ${fa.label.padEnd(24)} ${(ba ? kb(ba.wireBytes) : '-').padStart(11)} ${kb(fa.wireBytes).padStart(11)}  ${(fa.encoding ?? '-').padEnd(5)} ${fa.cacheControl ?? '-'}`)
      }
    }
  }
}

function reportExplorer (fx, line) {
  line()
  line(`Fact Explorer — pre-plan vs now   ${fx.findings.join(' ')}`)
  if (fx.error) { line(`  ${fx.error}`); return }
  const before = new Map(fx.runs.filter((x) => x.side === 'before').map((x) => [x.app, x]))
  const after = new Map(fx.runs.filter((x) => x.side === 'after').map((x) => [x.app, x]))
  for (const app of [...new Set(fx.runs.map((x) => x.app))]) {
    const b = before.get(app)
    const f = after.get(app)
    line()
    line(`  ${app}`)
    const L = 36
    const o = (k, fmt) => cmp(b?.opening[k], f?.opening[k], fmt)
    line(`    ── opening the explorer`)
    line(`    ${'FGM bytes over the wire'.padEnd(L)} ${cmp(b?.opening.groups['fgm-data'].bytes, f?.opening.groups['fgm-data'].bytes, kb)}`)
    line(`    ${'FGM requests'.padEnd(L)} ${b?.opening.groups['fgm-data'].n} → ${f?.opening.groups['fgm-data'].n}`)
    line(`    ${'whole graph fetched?'.padEnd(L)} ${b?.opening.wholeGraphFetches ? 'yes' : 'no'} → ${f?.opening.wholeGraphFetches ? 'yes' : 'no'}`)
    line(`    ${'first node on the canvas'.padEnd(L)} ${o('firstNodeMs', ms)}`)
    line(`    ${'canvas settled'.padEnd(L)} ${o('settleMs', ms)}`)
    line(`    ${'nodes drawn'.padEnd(L)} ${b?.opening.rfNodes} → ${f?.opening.rfNodes}`)
    line(`    ${'DOM under the canvas'.padEnd(L)} ${b?.opening.domUnderViewport} → ${f?.opening.domUnderViewport}`)
    line(`    ${'minimap nodes'.padEnd(L)} ${b?.opening.miniMapNodes} → ${f?.opening.miniMapNodes}`)
    line(`    ${'main thread blocked'.padEnd(L)} ${o('blockingMs', ms)}`)
    line(`    ${'pan frame p50 / p95'.padEnd(L)} ${pair(b?.opening.frames.p50, f?.opening.frames.p50, ms)}  /  ${pair(b?.opening.frames.p95, f?.opening.frames.p95, ms)}`)
    if (b?.full || f?.full) {
      line(`    ── full graph, on demand`)
      line(`    ${'FGM bytes over the wire'.padEnd(L)} ${cmp(b?.full?.groups['fgm-data'].bytes ?? 0, f?.full?.groups['fgm-data'].bytes ?? 0, kb)}`)
      line(`    ${'settled'.padEnd(L)} ${pair(b?.full?.settleMs, f?.full?.settleMs, ms)}`)
      line(`    ${'nodes drawn'.padEnd(L)} ${pair(b?.full?.rfNodes, f?.full?.rfNodes, (n) => `${n}`)}`)
      line(`    ${'DOM under the canvas'.padEnd(L)} ${pair(b?.full?.domUnderViewport, f?.full?.domUnderViewport, (n) => `${n}`)}`)
      line(`    ${'minimap nodes'.padEnd(L)} ${pair(b?.full?.miniMapNodes, f?.full?.miniMapNodes, (n) => `${n}`)}`)
      line(`    ${'pan frame p50 / p95'.padEnd(L)} ${pair(b?.full?.frames.p50, f?.full?.frames.p50, ms)}  /  ${pair(b?.full?.frames.p95, f?.full?.frames.p95, ms)}`)
    }
  }
  line()
  line(`  FX-7 · the graph over the dev server's own transport`)
  line(`    ${'app'.padEnd(22)} ${'before'.padStart(24)} ${'after'.padStart(24)}`)
  for (const app of [...new Set((fx.transport.after ?? fx.transport.before ?? []).map((x) => x.app))]) {
    const b = fx.transport.before?.find((x) => x.app === app)
    const f = fx.transport.after?.find((x) => x.app === app)
    const cell = (x) => (x ? `${kb(x.wireBytes)} ${x.encoding ?? 'identity'}${x.revalidatedStatus === 304 ? ' 304' : ''}` : '-')
    line(`    ${app.padEnd(22)} ${cell(b).padStart(24)} ${cell(f).padStart(24)}`)
  }
}

function grp (g) { return `${g['taxpert-js'].n}/${g['taxpert-css'].n}/${g['taxpert-templates'].n}` }
function grpBytes (g) { return g['taxpert-js'].bytes + g['taxpert-css'].bytes + g['taxpert-templates'].bytes }

// Function declarations rather than const arrows: report() runs above them in module order, and a
// const in the temporal dead zone would throw after the measurements are taken and before they are
// printed — losing a run that took minutes to produce.
function kb (n) { return n == null ? '-' : `${(n / 1024).toLocaleString('en-US', { maximumFractionDigits: 0 })} KB` }
function ms (n) { return n == null ? '-' : `${Math.round(n).toLocaleString('en-US')} ms` }
function sum (rows, k) { return rows.reduce((t, r) => t + (r[k] ?? 0), 0) }
function sumBy (map, k) { return [...map.values()].reduce((t, r) => t + (r[k] ?? 0), 0) }
function pair (b, f, fmt) { return b == null || f == null ? ((b ?? f) == null ? '-' : fmt(b ?? f)) : `${fmt(b)} → ${fmt(f)}` }

function cmp (b, f, fmt) {
  if (b == null || f == null) return pair(b, f, fmt)
  const r = f > 0 ? b / f : 0
  const tail = r >= 1.15 ? `  ${r.toFixed(1)}×` : r > 0 && r <= 0.87 ? `  ${(1 / r).toFixed(1)}× slower` : '  —'
  return `${fmt(b)} → ${fmt(f)}${tail}`
}

// ---- plumbing ----------------------------------------------------------------------------------

function parseArgs (argv) {
  const o = { stages: [1, 2], sides: ['before', 'after'], apps: null, json: null, root: 'image', baseline: DEFAULT_BASELINE }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    // Stages are numbers for the two file-swap stages and names for the two artifact ones; both
    // live in one list so --stage 1,site is a legal and meaningful run.
    if (a === '--stage') o.stages = argv[++i].split(',').map((x) => (/^\d+$/.test(x) ? Number(x) : x))
    else if (a === '--baseline') o.baseline = path.resolve(argv[++i])
    else if (a === '--apps') o.apps = argv[++i].split(',')
    else if (a === '--json') o.json = argv[++i]
    else if (a === '--root') o.root = argv[++i]
    else if (a === '--no-ab') o.sides = ['after']
    else if (a === '--baseline-only') o.sides = ['before']
    else if (a === '-h' || a === '--help') { console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').filter((l) => l.startsWith('//')).join('\n')); process.exit(0) }
    else fail(`unknown argument: ${a}`)
  }
  return o
}

function gitShow (repo, ref) {
  return execSync(repo, ['git', 'show', ref])
}

function gitRev (repo) {
  try { return execSync(repo, ['git', 'rev-parse', '--short', 'HEAD']).trim() } catch { return '?' }
}

function execSync (cwd, [cmd, ...cmdArgs]) {
  return execFileSync(cmd, cmdArgs, { cwd, encoding: 'utf8', maxBuffer: 1 << 28 })
}

async function curl (url, extra = []) {
  const { stdout } = await execFile('curl', ['-sS', '--max-time', '180', ...extra, url], { maxBuffer: 1 << 28 })
  return stdout
}

function findMap (dir) {
  try {
    return execSync(ROOT, ['find', dir, '-name', 'main.mjs.map']).split('\n').filter(Boolean)
  } catch { return [] }
}

function statSize (p) { return statSync(p).size }
function sha256 (s) { return createHash('sha256').update(s).digest('hex') }

// Outside the repo on purpose: a harness that leaves untracked files behind in a checkout you are
// about to review the diff of is a harness you will stop trusting. Docker Desktop shares /private by
// default, which is where macOS puts this, so the nginx.conf bind mount below still resolves.
function scratch () { return (scratch.dir ??= mkdtempSync(path.join(tmpdir(), 'fbx-perf-'))) }
function sleep (ms) { return new Promise((r) => setTimeout(r, ms)) }
function fail (msg) { console.error(`perf.mjs: ${msg}`); process.exit(2) }
